"""Cria relacionamento entre fornecedor e conta

Revision ID: 90684d841368
Revises: 8d263824ebc1
Create Date: 2023-12-13 19:59:36.134886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90684d841368'
down_revision: Union[str, None] = '8d263824ebc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
